### ISSUE TITLE
Wrong docs - Dictionary expected in createThunkErrorHandlerMiddleware

### ISSUE THREAD

**Issue by AdamGold** [itaylor/thunk-centric-redux#1]
The way to pass an error handler to ``createThunkErrorHandlerMiddleware`` is:
```
createThunkErrorHandlerMiddleware({
	onError: errorHandler
})
```

When passed this way:
```
createThunkErrorHandlerMiddleware(errorHandler)
```

I get (expectedly, looking at the code) ``onError is not a function``. I can make a PR to sort this, if you want.

**Comment by itaylor** [comment]
Fixed, thanks for the bug report!
