### ISSUE TITLE
TypeScript definitions for redux-thunk-recursion-detect

### ISSUE THREAD

**Issue by sschottler** [itaylor/thunk-centric-redux#2]
It would be helpful to have TypeScript declaration files from redux-thunk in redux-thunk-recursion-detect. Right now, if I want to use redux-thunk-recursion-detect with strongly typed ThunkActions, I still need the redux-thunk package to import the ThunkAction type:

https://github.com/reduxjs/redux-thunk/blob/0e60b6264fb402afb328157c4337f5cc87a07b53/index.d.ts#L44

**Comment by itaylor** [comment]
Yeah, that's a good idea.  I'll add them soon.

**Comment by itaylor** [comment]
I tried to fix this with 1.1.0, but it looks like the published tarball excluded the .ts file.  I'm going to figure out why that happened and try again.

**Comment by itaylor** [comment]
Ok, it looks like the `index.d.ts` is there in `redux-thunk-recursion-detect@1.1.1`.  I'm not (yet) using Typescript in my own projects, so please let me know if there's something I missed.

Hmm... I'm actually thinking this maybe should have been copied into the `/dist/` folder and ended up in there twice, as `/dist/reduxThunkRecursionDetect.cjs.d.ts` and `dist/reduxThunkRecursionDetect.esm.d.ts`?  
@sschottler please let me know if it works as-is or if I need to change it.

**Comment by sschottler** [comment]
Just tried it and it seems to work. I'm only using `ThunkAction` so can't speak to any of the other types. If I right click in VS Code and go to definition on `ThunkAction` type for `redux-thunk`, it takes me to `index.d.ts` file in root of package folder, not dist folder, which is the same for `redux-thunk-recursion-detect@1.1.1` so it seems correct for my case (importing with Create react app 2.1.3). Thanks for fixing!
